sudo: required
dist: trusty
language: python
cache: pip
python:
  - 3.5
  - 3.6

before_install:
  - sudo add-apt-repository -y ppa:maxmind/ppa
  - sudo apt-get update
  - sudo apt-get install geoipupdate
  #- echo 'UserId 999999' | sudo tee /etc/GeoIP.conf > /dev/null
  #- echo 'LicenseKey 000000000000' | sudo tee -a /etc/GeoIP.conf > /dev/null
  - echo 'EditionIDs GeoLite2-Country GeoLite2-City GeoLite2-ASN' | sudo tee -a /etc/GeoIP.conf > /dev/null
  - sudo geoipupdate -v
  - pip install -r dev_requirements.txt

script:
  - python setup.py test
  - python setup.py sdist

notifications:
  email:
    on_success: never
    on_failure: never

deploy:
  provider: pypi
  user: wesyoung
  password:
    secure: hgNut7wtQ6l/3ifq792kMpe5mnu+C/Yg33LmbAVn8M1KMbZTALzZWHjTJxSe5Wuqjle9Cq0hOOFMrLFy20GylGVoew2iQ+rom6gJgdo9yYkbvpqxt8SRSdZawIS6aMUZazkXZX+DJWOnjqhP9ukNMSuhUAgDWvmIaSSJC0fN5Lvr9khBYmYeUp285UwuvIi0vS8aRL+rhPkRFfZHykHuJCylzuK6bU9cJ8xF2lMrcsQeCp/uBvqsnTDdTpHH/P6osdBRxMzMIG50sdpkC9NGxTNCGjkepyK0lmnpOwonYg81Lm1x59GedaeRrhgjGf4you6si6Ih6M8a350ST7YaBN3yFnTF1Vz/R+QiDZT9E7llrH5R+IOyk0c0yyw8quAYAG+1tZeLcOqLVQwYRGc9kkj6YmldV0bReptlw33F/KElfSMUzwt97oqkGtE+wGAxSRg1FfWWLER4kQYqyPZ+o/4+WGc6y140CQuxnuAx8AGktwiRvTHML5lDPgnnbcN2w2+lOvNGm736hEVonhcpR2JuQpPyBChivcFWLeP8Upj8XyVnzuceJCVeiFrIJhW0xF3ysFfMFNgET8zHnhKV1CERV6o8/oa89bkVjNZC4on6rtDRxcdBWwcgjH1trocUwCtX64TO1y5+/SrVdEekpL+/bDoCy8QNyxeTufyv5Y4=
  on:
    branch: master
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = "3.6"
